### ISSUE TITLE
[SKID] Ez Skid

### ISSUE THREAD

**Issue by Coolhacker1332** [ProdigyAPI/ProdigyXHack#261]
L Bitch

**Comment by AgrTheDev** [comment]
Bro forked and thought he was doing sum special 💀

**Comment by Coolhacker1332** [comment]
i got the source code

**Comment by AgrTheDev** [comment]
yeah... its open source thats kinda the point

**Comment by afkvido** [comment]
# 💀 
CoolHacker1332
